# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Skely'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["bastardkb/skeletyl/blackpill"]'
      merge: '["Bastardkb/bastardkb-qmk/bkb-master qmk/qmk_firmware/master"]'
